CREATE TABLE IF NOT EXISTS `apam_master_document_model_field_detail` (
  `master_document_model_id` INT UNSIGNED NOT NULL,
  `master_document_model_field_id` INT UNSIGNED NOT NULL,
  `master_document_model_field_seq_id` INT UNSIGNED NOT NULL,
  `model_def_field_source_id` INT UNSIGNED NOT NULL,
  `model_def_field_alignment_type_id` INT UNSIGNED NOT NULL,
  `model_def_field_parse_type_id` INT UNSIGNED NOT NULL DEFAULT '20',
  `block_id` varchar(38) NOT NULL DEFAULT '',
  `field_format` varchar(128) DEFAULT NULL,
  `classifier_text` varchar(128) DEFAULT NULL,
  `page_number` INT UNSIGNED DEFAULT NULL,
  `table_number` INT UNSIGNED DEFAULT NULL,
  `table_row_index` INT UNSIGNED DEFAULT NULL,
  `table_col_index` INT UNSIGNED DEFAULT NULL,
  `boundingbox_left` decimal(24,20) DEFAULT NULL,
  `boundingbox_top` decimal(24,20) DEFAULT NULL,
  `boundingbox_width` decimal(24,20) DEFAULT NULL,
  `boundingbox_height` decimal(24,20) DEFAULT NULL,
  `confidence_level` decimal(24,20) DEFAULT NULL,
  `internal_comment` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`master_document_model_id`,`master_document_model_field_id`,`master_document_model_field_seq_id`),
  KEY `FK_apam_master_document_model_field_detail_1` (`master_document_model_id`,`master_document_model_field_id`),
  KEY `FK_apam_master_document_model_field_detail_2` (`model_def_field_source_id`),
  KEY `FK_apam_master_document_model_field_detail_3` (`model_def_field_alignment_type_id`),
  KEY `FK_apam_master_document_model_field_detail_4_idx` (`model_def_field_parse_type_id`),
  CONSTRAINT `FK_apam_master_document_model_field_detail_1` FOREIGN KEY (`master_document_model_id`, `master_document_model_field_id`) REFERENCES `apam_master_document_model_field` (`master_document_model_id`, `master_document_model_field_id`),
  CONSTRAINT `FK_apam_master_document_model_field_detail_2` FOREIGN KEY (`model_def_field_source_id`) REFERENCES `apai_model_def_field_source` (`model_def_field_source_id`),
  CONSTRAINT `FK_apam_master_document_model_field_detail_3` FOREIGN KEY (`model_def_field_alignment_type_id`) REFERENCES `apai_model_def_field_alignment_type` (`model_def_field_alignment_type_id`),
  CONSTRAINT `FK_apam_master_document_model_field_detail_4` FOREIGN KEY (`model_def_field_parse_type_id`) REFERENCES `apai_model_def_field_parse_type` (`model_def_field_parse_type_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

