CREATE TABLE IF NOT EXISTS `apad_invoice_document` (
  `company_code` INT NOT NULL,
  `invoice_document_id` INT UNSIGNED NOT NULL,
  `invoice_document_file_location` VARCHAR(1024) NULL DEFAULT NULL,
  `invoice_document_status_id` INT UNSIGNED NOT NULL,
  `invoice_document_status_attribute` CHAR(1) NULL DEFAULT NULL,
  `duplicate_invoice_flag` CHAR(1) NOT NULL,
  `master_document_model_id` INT UNSIGNED NULL DEFAULT NULL,
  `document_model_request_id` INT UNSIGNED NULL DEFAULT NULL,
  `vendor_code` VARCHAR(12) NULL DEFAULT NULL,
  `site_id` VARCHAR(32) NULL DEFAULT NULL,
  `invoice_number` VARCHAR(32) NULL DEFAULT NULL,
  `invoice_date` DATE NULL DEFAULT NULL,
  `due_date` DATE NULL DEFAULT NULL,
  `service_term_start_date` DATE NULL DEFAULT NULL,
  `service_term_end_date` DATE NULL DEFAULT NULL,
  `payment_term_code` VARCHAR(32) NULL DEFAULT NULL,
  `currency_code` VARCHAR(32) NULL DEFAULT NULL,
  `scanned_total` DOUBLE NOT NULL DEFAULT 0,
  `po_code` VARCHAR(32) NULL,
  `replaced_by_invoice_document_file_location` VARCHAR(1024) NULL DEFAULT NULL,
  `transaction_id` VARCHAR(32) NULL,
  `is_deleted` TINYINT NOT NULL,
  `model_def_id` INT UNSIGNED NOT NULL DEFAULT 1,
  `create_id` VARCHAR(32) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `modify_id` VARCHAR(32) NULL DEFAULT NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`company_code`, `invoice_document_id`),
  KEY `FK_apad_invoice_document_1` (`invoice_document_status_id` ASC),
  KEY `FK_apad_invoice_document_2` (`master_document_model_id` ASC),
  KEY `FK_apad_invoice_document__apam_document_model_request` (`document_model_request_id` ASC),
  KEY `FK_apad_invoice_document_3` (`model_def_id` ASC),
  CONSTRAINT `FK_apad_invoice_document_1` FOREIGN KEY (`invoice_document_status_id`) REFERENCES {COMMON_DATABASE}.`apai_invoice_document_status` (`invoice_document_status_id`),
  CONSTRAINT `FK_apad_invoice_document_2` FOREIGN KEY (`master_document_model_id`) REFERENCES {COMMON_DATABASE}.`apam_master_document_model` (`master_document_model_id`),
  CONSTRAINT `FK_apad_invoice_document__apam_document_model_request` FOREIGN KEY (`document_model_request_id`) REFERENCES `apam_document_model_request` (`document_model_request_id`),
  CONSTRAINT `FK_apad_invoice_document_3` FOREIGN KEY (`model_def_id`) REFERENCES {COMMON_DATABASE}.`apai_model_def` (`model_def_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

