DELIMITER $$
DROP PROCEDURE IF EXISTS apas_companyapprovalconfiguration_save;$$

CREATE PROCEDURE apas_companyapprovalconfiguration_save(
	IN company_code_param                                   INT,
	IN model_def_id_param                                   INT UNSIGNED,
	IN routing_number_of_approval_levels_param              INT,
	IN approval_level_1_short_name_param                    VARCHAR(64), 
	IN approval_level_1_name_param                          VARCHAR(64), 
	IN approval_level_1_status_name_param                   VARCHAR(64), 
	IN approval_level_1_accept_name_param                   VARCHAR(64), 
	IN approval_level_1_reject_name_param                   VARCHAR(64), 
	IN approval_level_1_allow_invoice_editing_flag_param    CHAR(1),
	IN approval_level_2_short_name_param                    VARCHAR(64), 
	IN approval_level_2_name_param                          VARCHAR(64), 
	IN approval_level_2_status_name_param                   VARCHAR(64), 
	IN approval_level_2_accept_name_param                   VARCHAR(64), 
	IN approval_level_2_reject_name_param                   VARCHAR(64), 
	IN approval_level_2_allow_invoice_editing_flag_param    CHAR(1),
	IN approval_level_3_short_name_param                    VARCHAR(64), 
	IN approval_level_3_name_param                          VARCHAR(64), 
	IN approval_level_3_status_name_param                   VARCHAR(64), 
	IN approval_level_3_accept_name_param                   VARCHAR(64), 
	IN approval_level_3_reject_name_param                   VARCHAR(64), 
	IN approval_level_3_allow_invoice_editing_flag_param    CHAR(1),
	IN approval_level_4_short_name_param                    VARCHAR(64), 
	IN approval_level_4_name_param                          VARCHAR(64), 
	IN approval_level_4_status_name_param                   VARCHAR(64), 
	IN approval_level_4_accept_name_param                   VARCHAR(64), 
	IN approval_level_4_reject_name_param                   VARCHAR(64), 
	IN approval_level_4_allow_invoice_editing_flag_param    CHAR(1),
	IN approval_level_5_short_name_param                    VARCHAR(64), 
	IN approval_level_5_name_param                          VARCHAR(64), 
	IN approval_level_5_status_name_param                   VARCHAR(64), 
	IN approval_level_5_accept_name_param                   VARCHAR(64), 
	IN approval_level_5_reject_name_param                   VARCHAR(64), 
	IN approval_level_5_allow_invoice_editing_flag_param    CHAR(1)
)
BEGIN
	IF NOT EXISTS (SELECT 1 FROM apam_company_approval_configuration WHERE company_code = company_code_param AND model_def_id = model_def_id_param) THEN
		INSERT INTO apam_company_approval_configuration
		(
			company_code,
			model_def_id,
			routing_number_of_approval_levels,
			approval_level_1_short_name,
			approval_level_1_name,
			approval_level_1_status_name,
			approval_level_1_accept_name,
			approval_level_1_reject_name,
			approval_level_1_allow_invoice_editing_flag,
			approval_level_2_short_name,
			approval_level_2_name,
			approval_level_2_status_name,
			approval_level_2_accept_name,
			approval_level_2_reject_name,
			approval_level_2_allow_invoice_editing_flag,
			approval_level_3_short_name,
			approval_level_3_name,
			approval_level_3_status_name,
			approval_level_3_accept_name,
			approval_level_3_reject_name,
			approval_level_3_allow_invoice_editing_flag,
			approval_level_4_short_name,
			approval_level_4_name,
			approval_level_4_status_name,
			approval_level_4_accept_name,
			approval_level_4_reject_name,
			approval_level_4_allow_invoice_editing_flag,
			approval_level_5_short_name,
			approval_level_5_name,
			approval_level_5_status_name,
			approval_level_5_accept_name,
			approval_level_5_reject_name,
			approval_level_5_allow_invoice_editing_flag
		)
		SELECT
			company_code_param,
			model_def_id_param,
			routing_number_of_approval_levels_param,
			approval_level_1_short_name_param,
			approval_level_1_name_param,
			approval_level_1_status_name_param,
			approval_level_1_accept_name_param,
			approval_level_1_reject_name_param,
			approval_level_1_allow_invoice_editing_flag_param,
			approval_level_2_short_name_param,
			approval_level_2_name_param,
			approval_level_2_status_name_param,
			approval_level_2_accept_name_param,
			approval_level_2_reject_name_param,
			approval_level_2_allow_invoice_editing_flag_param,
			approval_level_3_short_name_param,
			approval_level_3_name_param,
			approval_level_3_status_name_param,
			approval_level_3_accept_name_param,
			approval_level_3_reject_name_param,
			approval_level_3_allow_invoice_editing_flag_param,
			approval_level_4_short_name_param,
			approval_level_4_name_param,
			approval_level_4_status_name_param,
			approval_level_4_accept_name_param,
			approval_level_4_reject_name_param,
			approval_level_4_allow_invoice_editing_flag_param,
			approval_level_5_short_name_param,
			approval_level_5_name_param,
			approval_level_5_status_name_param,
			approval_level_5_accept_name_param,
			approval_level_5_reject_name_param,
			approval_level_5_allow_invoice_editing_flag_param;
	ELSE
		UPDATE
			apam_company_approval_configuration
		SET
			routing_number_of_approval_levels			 = routing_number_of_approval_levels_param,
			approval_level_1_short_name					 = approval_level_1_short_name_param,
			approval_level_1_name						 = approval_level_1_name_param,
			approval_level_1_status_name				 = approval_level_1_status_name_param,
			approval_level_1_accept_name				 = approval_level_1_accept_name_param,
			approval_level_1_reject_name				 = approval_level_1_reject_name_param,
			approval_level_1_allow_invoice_editing_flag	 = approval_level_1_allow_invoice_editing_flag_param,
			approval_level_2_short_name					 = approval_level_2_short_name_param,
			approval_level_2_name						 = approval_level_2_name_param,
			approval_level_2_status_name				 = approval_level_2_status_name_param,
			approval_level_2_accept_name				 = approval_level_2_accept_name_param,
			approval_level_2_reject_name				 = approval_level_2_reject_name_param,
			approval_level_2_allow_invoice_editing_flag	 = approval_level_2_allow_invoice_editing_flag_param,
			approval_level_3_short_name					 = approval_level_3_short_name_param,
			approval_level_3_name						 = approval_level_3_name_param,
			approval_level_3_status_name				 = approval_level_3_status_name_param,
			approval_level_3_accept_name				 = approval_level_3_accept_name_param,
			approval_level_3_reject_name				 = approval_level_3_reject_name_param,
			approval_level_3_allow_invoice_editing_flag	 = approval_level_3_allow_invoice_editing_flag_param,
			approval_level_4_short_name					 = approval_level_4_short_name_param,
			approval_level_4_name						 = approval_level_4_name_param,
			approval_level_4_status_name				 = approval_level_4_status_name_param,
			approval_level_4_accept_name				 = approval_level_4_accept_name_param,
			approval_level_4_reject_name				 = approval_level_4_reject_name_param,
			approval_level_4_allow_invoice_editing_flag	 = approval_level_4_allow_invoice_editing_flag_param,
			approval_level_5_short_name					 = approval_level_5_short_name_param,
			approval_level_5_name						 = approval_level_5_name_param,
			approval_level_5_status_name				 = approval_level_5_status_name_param,
			approval_level_5_accept_name				 = approval_level_5_accept_name_param,
			approval_level_5_reject_name				 = approval_level_5_reject_name_param,
			approval_level_5_allow_invoice_editing_flag	 = approval_level_5_allow_invoice_editing_flag_param
		WHERE
			company_code = company_code_param
			AND model_def_id = model_def_id_param;
	END IF;
END$$
DELIMITER ;

