//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NexelusApp.Service.eSMWebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EsmWebServiceSoap", Namespace="Paradigm.Esm.WebService")]
    public partial class EsmWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetEditionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReleaseDateOperationCompleted;
        
        private AuthToken authTokenValueField;
        
        private System.Threading.SendOrPostCallback AuthenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInstalledCompanyListOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsAuthenticatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAuthenticationTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTrxTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReferenceDataRecordsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReferenceAvailableFieldListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportingAvailableParametersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportingDataRecordsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSysNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReplaceWithGenNamesOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerformActionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExpenseTransactionImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetExpenseTransactionImageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EsmWebService() {
            this.Url = global::NexelusApp.Service.Properties.Settings.Default.NexelusApp_Service_eSMWebService_EsmWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthToken AuthTokenValue {
            get {
                return this.authTokenValueField;
            }
            set {
                this.authTokenValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetEditionCompletedEventHandler GetEditionCompleted;
        
        /// <remarks/>
        public event GetVersionCompletedEventHandler GetVersionCompleted;
        
        /// <remarks/>
        public event GetReleaseDateCompletedEventHandler GetReleaseDateCompleted;
        
        /// <remarks/>
        public event AuthenticateCompletedEventHandler AuthenticateCompleted;
        
        /// <remarks/>
        public event GetInstalledCompanyListCompletedEventHandler GetInstalledCompanyListCompleted;
        
        /// <remarks/>
        public event IsAuthenticatedCompletedEventHandler IsAuthenticatedCompleted;
        
        /// <remarks/>
        public event GetAuthenticationTokenCompletedEventHandler GetAuthenticationTokenCompleted;
        
        /// <remarks/>
        public event GetTrxTypesCompletedEventHandler GetTrxTypesCompleted;
        
        /// <remarks/>
        public event GetReferenceDataRecordsCompletedEventHandler GetReferenceDataRecordsCompleted;
        
        /// <remarks/>
        public event GetReferenceAvailableFieldListCompletedEventHandler GetReferenceAvailableFieldListCompleted;
        
        /// <remarks/>
        public event GetReportingAvailableParametersCompletedEventHandler GetReportingAvailableParametersCompleted;
        
        /// <remarks/>
        public event GetReportingDataRecordsCompletedEventHandler GetReportingDataRecordsCompleted;
        
        /// <remarks/>
        public event GetSysNameCompletedEventHandler GetSysNameCompleted;
        
        /// <remarks/>
        public event ReplaceWithGenNamesCompletedEventHandler ReplaceWithGenNamesCompleted;
        
        /// <remarks/>
        public event PerformActionCompletedEventHandler PerformActionCompleted;
        
        /// <remarks/>
        public event GetExpenseTransactionImageCompletedEventHandler GetExpenseTransactionImageCompleted;
        
        /// <remarks/>
        public event SetExpenseTransactionImageCompletedEventHandler SetExpenseTransactionImageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/GetEdition", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEdition() {
            object[] results = this.Invoke("GetEdition", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEditionAsync() {
            this.GetEditionAsync(null);
        }
        
        /// <remarks/>
        public void GetEditionAsync(object userState) {
            if ((this.GetEditionOperationCompleted == null)) {
                this.GetEditionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEditionOperationCompleted);
            }
            this.InvokeAsync("GetEdition", new object[0], this.GetEditionOperationCompleted, userState);
        }
        
        private void OnGetEditionOperationCompleted(object arg) {
            if ((this.GetEditionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEditionCompleted(this, new GetEditionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/GetVersion", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetVersion() {
            object[] results = this.Invoke("GetVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetVersionAsync() {
            this.GetVersionAsync(null);
        }
        
        /// <remarks/>
        public void GetVersionAsync(object userState) {
            if ((this.GetVersionOperationCompleted == null)) {
                this.GetVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVersionOperationCompleted);
            }
            this.InvokeAsync("GetVersion", new object[0], this.GetVersionOperationCompleted, userState);
        }
        
        private void OnGetVersionOperationCompleted(object arg) {
            if ((this.GetVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVersionCompleted(this, new GetVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/GetReleaseDate", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetReleaseDate() {
            object[] results = this.Invoke("GetReleaseDate", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetReleaseDateAsync() {
            this.GetReleaseDateAsync(null);
        }
        
        /// <remarks/>
        public void GetReleaseDateAsync(object userState) {
            if ((this.GetReleaseDateOperationCompleted == null)) {
                this.GetReleaseDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReleaseDateOperationCompleted);
            }
            this.InvokeAsync("GetReleaseDate", new object[0], this.GetReleaseDateOperationCompleted, userState);
        }
        
        private void OnGetReleaseDateOperationCompleted(object arg) {
            if ((this.GetReleaseDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReleaseDateCompleted(this, new GetReleaseDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthTokenValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/Authenticate", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Authenticate(string username, string password, int company, string userGroupCode) {
            this.Invoke("Authenticate", new object[] {
                        username,
                        password,
                        company,
                        userGroupCode});
        }
        
        /// <remarks/>
        public void AuthenticateAsync(string username, string password, int company, string userGroupCode) {
            this.AuthenticateAsync(username, password, company, userGroupCode, null);
        }
        
        /// <remarks/>
        public void AuthenticateAsync(string username, string password, int company, string userGroupCode, object userState) {
            if ((this.AuthenticateOperationCompleted == null)) {
                this.AuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateOperationCompleted);
            }
            this.InvokeAsync("Authenticate", new object[] {
                        username,
                        password,
                        company,
                        userGroupCode}, this.AuthenticateOperationCompleted, userState);
        }
        
        private void OnAuthenticateOperationCompleted(object arg) {
            if ((this.AuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/GetInstalledCompanyList", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CompanyLight[] GetInstalledCompanyList() {
            object[] results = this.Invoke("GetInstalledCompanyList", new object[0]);
            return ((CompanyLight[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInstalledCompanyListAsync() {
            this.GetInstalledCompanyListAsync(null);
        }
        
        /// <remarks/>
        public void GetInstalledCompanyListAsync(object userState) {
            if ((this.GetInstalledCompanyListOperationCompleted == null)) {
                this.GetInstalledCompanyListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInstalledCompanyListOperationCompleted);
            }
            this.InvokeAsync("GetInstalledCompanyList", new object[0], this.GetInstalledCompanyListOperationCompleted, userState);
        }
        
        private void OnGetInstalledCompanyListOperationCompleted(object arg) {
            if ((this.GetInstalledCompanyListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInstalledCompanyListCompleted(this, new GetInstalledCompanyListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthTokenValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/IsAuthenticated", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsAuthenticated() {
            object[] results = this.Invoke("IsAuthenticated", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsAuthenticatedAsync() {
            this.IsAuthenticatedAsync(null);
        }
        
        /// <remarks/>
        public void IsAuthenticatedAsync(object userState) {
            if ((this.IsAuthenticatedOperationCompleted == null)) {
                this.IsAuthenticatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsAuthenticatedOperationCompleted);
            }
            this.InvokeAsync("IsAuthenticated", new object[0], this.IsAuthenticatedOperationCompleted, userState);
        }
        
        private void OnIsAuthenticatedOperationCompleted(object arg) {
            if ((this.IsAuthenticatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsAuthenticatedCompleted(this, new IsAuthenticatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthTokenValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/GetAuthenticationToken", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AuthToken GetAuthenticationToken() {
            object[] results = this.Invoke("GetAuthenticationToken", new object[0]);
            return ((AuthToken)(results[0]));
        }
        
        /// <remarks/>
        public void GetAuthenticationTokenAsync() {
            this.GetAuthenticationTokenAsync(null);
        }
        
        /// <remarks/>
        public void GetAuthenticationTokenAsync(object userState) {
            if ((this.GetAuthenticationTokenOperationCompleted == null)) {
                this.GetAuthenticationTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAuthenticationTokenOperationCompleted);
            }
            this.InvokeAsync("GetAuthenticationToken", new object[0], this.GetAuthenticationTokenOperationCompleted, userState);
        }
        
        private void OnGetAuthenticationTokenOperationCompleted(object arg) {
            if ((this.GetAuthenticationTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAuthenticationTokenCompleted(this, new GetAuthenticationTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/GetTrxTypes", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TrxType GetTrxTypes() {
            object[] results = this.Invoke("GetTrxTypes", new object[0]);
            return ((TrxType)(results[0]));
        }
        
        /// <remarks/>
        public void GetTrxTypesAsync() {
            this.GetTrxTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetTrxTypesAsync(object userState) {
            if ((this.GetTrxTypesOperationCompleted == null)) {
                this.GetTrxTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTrxTypesOperationCompleted);
            }
            this.InvokeAsync("GetTrxTypes", new object[0], this.GetTrxTypesOperationCompleted, userState);
        }
        
        private void OnGetTrxTypesOperationCompleted(object arg) {
            if ((this.GetTrxTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTrxTypesCompleted(this, new GetTrxTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthTokenValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/GetReferenceDataRecords", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataRecords GetReferenceDataRecords(REFERENCE_DATA_RECORD_TYPE DataRecordType, FieldAttribute[] fieldsList, string filter, string sortFields) {
            object[] results = this.Invoke("GetReferenceDataRecords", new object[] {
                        DataRecordType,
                        fieldsList,
                        filter,
                        sortFields});
            return ((DataRecords)(results[0]));
        }
        
        /// <remarks/>
        public void GetReferenceDataRecordsAsync(REFERENCE_DATA_RECORD_TYPE DataRecordType, FieldAttribute[] fieldsList, string filter, string sortFields) {
            this.GetReferenceDataRecordsAsync(DataRecordType, fieldsList, filter, sortFields, null);
        }
        
        /// <remarks/>
        public void GetReferenceDataRecordsAsync(REFERENCE_DATA_RECORD_TYPE DataRecordType, FieldAttribute[] fieldsList, string filter, string sortFields, object userState) {
            if ((this.GetReferenceDataRecordsOperationCompleted == null)) {
                this.GetReferenceDataRecordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReferenceDataRecordsOperationCompleted);
            }
            this.InvokeAsync("GetReferenceDataRecords", new object[] {
                        DataRecordType,
                        fieldsList,
                        filter,
                        sortFields}, this.GetReferenceDataRecordsOperationCompleted, userState);
        }
        
        private void OnGetReferenceDataRecordsOperationCompleted(object arg) {
            if ((this.GetReferenceDataRecordsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReferenceDataRecordsCompleted(this, new GetReferenceDataRecordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthTokenValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/GetReferenceAvailableFieldList", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FieldAttribute[] GetReferenceAvailableFieldList(REFERENCE_DATA_RECORD_TYPE DataRecordType) {
            object[] results = this.Invoke("GetReferenceAvailableFieldList", new object[] {
                        DataRecordType});
            return ((FieldAttribute[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReferenceAvailableFieldListAsync(REFERENCE_DATA_RECORD_TYPE DataRecordType) {
            this.GetReferenceAvailableFieldListAsync(DataRecordType, null);
        }
        
        /// <remarks/>
        public void GetReferenceAvailableFieldListAsync(REFERENCE_DATA_RECORD_TYPE DataRecordType, object userState) {
            if ((this.GetReferenceAvailableFieldListOperationCompleted == null)) {
                this.GetReferenceAvailableFieldListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReferenceAvailableFieldListOperationCompleted);
            }
            this.InvokeAsync("GetReferenceAvailableFieldList", new object[] {
                        DataRecordType}, this.GetReferenceAvailableFieldListOperationCompleted, userState);
        }
        
        private void OnGetReferenceAvailableFieldListOperationCompleted(object arg) {
            if ((this.GetReferenceAvailableFieldListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReferenceAvailableFieldListCompleted(this, new GetReferenceAvailableFieldListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthTokenValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/GetReportingAvailableParameters", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FieldAttribute[] GetReportingAvailableParameters(REPORTING_DATA_RECORD_TYPE DataRecordType) {
            object[] results = this.Invoke("GetReportingAvailableParameters", new object[] {
                        DataRecordType});
            return ((FieldAttribute[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReportingAvailableParametersAsync(REPORTING_DATA_RECORD_TYPE DataRecordType) {
            this.GetReportingAvailableParametersAsync(DataRecordType, null);
        }
        
        /// <remarks/>
        public void GetReportingAvailableParametersAsync(REPORTING_DATA_RECORD_TYPE DataRecordType, object userState) {
            if ((this.GetReportingAvailableParametersOperationCompleted == null)) {
                this.GetReportingAvailableParametersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportingAvailableParametersOperationCompleted);
            }
            this.InvokeAsync("GetReportingAvailableParameters", new object[] {
                        DataRecordType}, this.GetReportingAvailableParametersOperationCompleted, userState);
        }
        
        private void OnGetReportingAvailableParametersOperationCompleted(object arg) {
            if ((this.GetReportingAvailableParametersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportingAvailableParametersCompleted(this, new GetReportingAvailableParametersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthTokenValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/GetReportingDataRecords", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataRecords GetReportingDataRecords(REPORTING_DATA_RECORD_TYPE DataRecordType, NameValue[] spParams, FieldAttribute[] fieldsList) {
            object[] results = this.Invoke("GetReportingDataRecords", new object[] {
                        DataRecordType,
                        spParams,
                        fieldsList});
            return ((DataRecords)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportingDataRecordsAsync(REPORTING_DATA_RECORD_TYPE DataRecordType, NameValue[] spParams, FieldAttribute[] fieldsList) {
            this.GetReportingDataRecordsAsync(DataRecordType, spParams, fieldsList, null);
        }
        
        /// <remarks/>
        public void GetReportingDataRecordsAsync(REPORTING_DATA_RECORD_TYPE DataRecordType, NameValue[] spParams, FieldAttribute[] fieldsList, object userState) {
            if ((this.GetReportingDataRecordsOperationCompleted == null)) {
                this.GetReportingDataRecordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportingDataRecordsOperationCompleted);
            }
            this.InvokeAsync("GetReportingDataRecords", new object[] {
                        DataRecordType,
                        spParams,
                        fieldsList}, this.GetReportingDataRecordsOperationCompleted, userState);
        }
        
        private void OnGetReportingDataRecordsOperationCompleted(object arg) {
            if ((this.GetReportingDataRecordsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportingDataRecordsCompleted(this, new GetReportingDataRecordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthTokenValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/GetSysName", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSysName(string key) {
            object[] results = this.Invoke("GetSysName", new object[] {
                        key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSysNameAsync(string key) {
            this.GetSysNameAsync(key, null);
        }
        
        /// <remarks/>
        public void GetSysNameAsync(string key, object userState) {
            if ((this.GetSysNameOperationCompleted == null)) {
                this.GetSysNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSysNameOperationCompleted);
            }
            this.InvokeAsync("GetSysName", new object[] {
                        key}, this.GetSysNameOperationCompleted, userState);
        }
        
        private void OnGetSysNameOperationCompleted(object arg) {
            if ((this.GetSysNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSysNameCompleted(this, new GetSysNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthTokenValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/ReplaceWithGenNames", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReplaceWithGenNames(string msg, string start, string end) {
            object[] results = this.Invoke("ReplaceWithGenNames", new object[] {
                        msg,
                        start,
                        end});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReplaceWithGenNamesAsync(string msg, string start, string end) {
            this.ReplaceWithGenNamesAsync(msg, start, end, null);
        }
        
        /// <remarks/>
        public void ReplaceWithGenNamesAsync(string msg, string start, string end, object userState) {
            if ((this.ReplaceWithGenNamesOperationCompleted == null)) {
                this.ReplaceWithGenNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReplaceWithGenNamesOperationCompleted);
            }
            this.InvokeAsync("ReplaceWithGenNames", new object[] {
                        msg,
                        start,
                        end}, this.ReplaceWithGenNamesOperationCompleted, userState);
        }
        
        private void OnReplaceWithGenNamesOperationCompleted(object arg) {
            if ((this.ReplaceWithGenNamesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReplaceWithGenNamesCompleted(this, new ReplaceWithGenNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthTokenValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/PerformAction", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PerformAction(ACTION_TYPE DataRecordType, [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfNameValue")] [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)] NameValue[][] spParams) {
            object[] results = this.Invoke("PerformAction", new object[] {
                        DataRecordType,
                        spParams});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PerformActionAsync(ACTION_TYPE DataRecordType, NameValue[][] spParams) {
            this.PerformActionAsync(DataRecordType, spParams, null);
        }
        
        /// <remarks/>
        public void PerformActionAsync(ACTION_TYPE DataRecordType, NameValue[][] spParams, object userState) {
            if ((this.PerformActionOperationCompleted == null)) {
                this.PerformActionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerformActionOperationCompleted);
            }
            this.InvokeAsync("PerformAction", new object[] {
                        DataRecordType,
                        spParams}, this.PerformActionOperationCompleted, userState);
        }
        
        private void OnPerformActionOperationCompleted(object arg) {
            if ((this.PerformActionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerformActionCompleted(this, new PerformActionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthTokenValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/GetExpenseTransactionImage", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetExpenseTransactionImage(int company_code, string record_id, string transaction_id) {
            object[] results = this.Invoke("GetExpenseTransactionImage", new object[] {
                        company_code,
                        record_id,
                        transaction_id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetExpenseTransactionImageAsync(int company_code, string record_id, string transaction_id) {
            this.GetExpenseTransactionImageAsync(company_code, record_id, transaction_id, null);
        }
        
        /// <remarks/>
        public void GetExpenseTransactionImageAsync(int company_code, string record_id, string transaction_id, object userState) {
            if ((this.GetExpenseTransactionImageOperationCompleted == null)) {
                this.GetExpenseTransactionImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExpenseTransactionImageOperationCompleted);
            }
            this.InvokeAsync("GetExpenseTransactionImage", new object[] {
                        company_code,
                        record_id,
                        transaction_id}, this.GetExpenseTransactionImageOperationCompleted, userState);
        }
        
        private void OnGetExpenseTransactionImageOperationCompleted(object arg) {
            if ((this.GetExpenseTransactionImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExpenseTransactionImageCompleted(this, new GetExpenseTransactionImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthTokenValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Paradigm.Esm.WebService/SetExpenseTransactionImage", RequestNamespace="Paradigm.Esm.WebService", ResponseNamespace="Paradigm.Esm.WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SetExpenseTransactionImage(int company_code, string record_id, string transaction_id, string imageData) {
            object[] results = this.Invoke("SetExpenseTransactionImage", new object[] {
                        company_code,
                        record_id,
                        transaction_id,
                        imageData});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetExpenseTransactionImageAsync(int company_code, string record_id, string transaction_id, string imageData) {
            this.SetExpenseTransactionImageAsync(company_code, record_id, transaction_id, imageData, null);
        }
        
        /// <remarks/>
        public void SetExpenseTransactionImageAsync(int company_code, string record_id, string transaction_id, string imageData, object userState) {
            if ((this.SetExpenseTransactionImageOperationCompleted == null)) {
                this.SetExpenseTransactionImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetExpenseTransactionImageOperationCompleted);
            }
            this.InvokeAsync("SetExpenseTransactionImage", new object[] {
                        company_code,
                        record_id,
                        transaction_id,
                        imageData}, this.SetExpenseTransactionImageOperationCompleted, userState);
        }
        
        private void OnSetExpenseTransactionImageOperationCompleted(object arg) {
            if ((this.SetExpenseTransactionImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetExpenseTransactionImageCompleted(this, new SetExpenseTransactionImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Paradigm.Esm.WebService")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="Paradigm.Esm.WebService", IsNullable=false)]
    public partial class AuthToken : System.Web.Services.Protocols.SoapHeader {
        
        private UserInfo wSUserInfoField;
        
        private bool isAuthenticatedField;
        
        private System.DateTime loginDateTimeField;
        
        private GENSysNames sysNamesField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public UserInfo WSUserInfo {
            get {
                return this.wSUserInfoField;
            }
            set {
                this.wSUserInfoField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAuthenticated {
            get {
                return this.isAuthenticatedField;
            }
            set {
                this.isAuthenticatedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LoginDateTime {
            get {
                return this.loginDateTimeField;
            }
            set {
                this.loginDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public GENSysNames SysNames {
            get {
                return this.sysNamesField;
            }
            set {
                this.sysNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Paradigm.Esm.WebService")]
    public partial class UserInfo {
        
        private string loginIDField;
        
        private string passwordField;
        
        private int companyCodeField;
        
        private string resourceIDField;
        
        private string user_group_codeField;
        
        private string dateFormatField;
        
        /// <remarks/>
        public string loginID {
            get {
                return this.loginIDField;
            }
            set {
                this.loginIDField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int companyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string resourceID {
            get {
                return this.resourceIDField;
            }
            set {
                this.resourceIDField = value;
            }
        }
        
        /// <remarks/>
        public string user_group_code {
            get {
                return this.user_group_codeField;
            }
            set {
                this.user_group_codeField = value;
            }
        }
        
        /// <remarks/>
        public string dateFormat {
            get {
                return this.dateFormatField;
            }
            set {
                this.dateFormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Paradigm.Esm.WebService")]
    public partial class DataRecords {
        
        private FieldAttribute[] filedListField;
        
        private object[][] dataField;
        
        /// <remarks/>
        public FieldAttribute[] FiledList {
            get {
                return this.filedListField;
            }
            set {
                this.filedListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfAnyType")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public object[][] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Paradigm.Esm.WebService")]
    public partial class FieldAttribute {
        
        private string fieldNameField;
        
        private string eSM_FieldNameField;
        
        private FIELD_TYPE fieldTypeField;
        
        private int fieldLengthField;
        
        private bool isNullableField;
        
        /// <remarks/>
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        /// <remarks/>
        public string ESM_FieldName {
            get {
                return this.eSM_FieldNameField;
            }
            set {
                this.eSM_FieldNameField = value;
            }
        }
        
        /// <remarks/>
        public FIELD_TYPE FieldType {
            get {
                return this.fieldTypeField;
            }
            set {
                this.fieldTypeField = value;
            }
        }
        
        /// <remarks/>
        public int FieldLength {
            get {
                return this.fieldLengthField;
            }
            set {
                this.fieldLengthField = value;
            }
        }
        
        /// <remarks/>
        public bool IsNullable {
            get {
                return this.isNullableField;
            }
            set {
                this.isNullableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Paradigm.Esm.WebService")]
    public enum FIELD_TYPE {
        
        /// <remarks/>
        INT,
        
        /// <remarks/>
        FLOAT,
        
        /// <remarks/>
        STRING,
        
        /// <remarks/>
        DATETIME,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Paradigm.Esm.WebService")]
    public partial class TrxType {
        
        private int time__WO_H_R_TimeField;
        
        private int time__WO_S_R_TimeField;
        
        private int time__WO_SUB_R_TimeField;
        
        private int time__FeesField;
        
        private int expenses__ExpensesField;
        
        private int expenses__WO_ExpenseField;
        
        /// <remarks/>
        public int Time__WO_H_R_Time {
            get {
                return this.time__WO_H_R_TimeField;
            }
            set {
                this.time__WO_H_R_TimeField = value;
            }
        }
        
        /// <remarks/>
        public int Time__WO_S_R_Time {
            get {
                return this.time__WO_S_R_TimeField;
            }
            set {
                this.time__WO_S_R_TimeField = value;
            }
        }
        
        /// <remarks/>
        public int Time__WO_SUB_R_Time {
            get {
                return this.time__WO_SUB_R_TimeField;
            }
            set {
                this.time__WO_SUB_R_TimeField = value;
            }
        }
        
        /// <remarks/>
        public int Time__Fees {
            get {
                return this.time__FeesField;
            }
            set {
                this.time__FeesField = value;
            }
        }
        
        /// <remarks/>
        public int Expenses__Expenses {
            get {
                return this.expenses__ExpensesField;
            }
            set {
                this.expenses__ExpensesField = value;
            }
        }
        
        /// <remarks/>
        public int Expenses__WO_Expense {
            get {
                return this.expenses__WO_ExpenseField;
            }
            set {
                this.expenses__WO_ExpenseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Paradigm.Esm.WebService")]
    public partial class CompanyLight {
        
        private int companyCodeField;
        
        private string shortNameField;
        
        /// <remarks/>
        public int CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Paradigm.Esm.WebService")]
    public partial class NameValue {
        
        private string nameField;
        
        private object valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Paradigm.Esm.WebService")]
    public partial class GENSysNames {
        
        private string lEVEL2_SYSNAMEField;
        
        private string lEVEL3_SYSNAMEField;
        
        private string oRG_UNIT_SYSNAMEField;
        
        private string lOCATION_SYSNAMEField;
        
        private string cOMPANY_SYSNAMEField;
        
        private string cLIENT_SYSNAMEField;
        
        private string pOSITION_SYSNAMEField;
        
        private string tASK_SYSNAMEField;
        
        private string dEPARTMENT_SYSNAMEField;
        
        private string cLASS_SYSNAMEField;
        
        private string eXPTYPES_SYSNAME_NAMEField;
        
        private string eXPTYPES_SYSNAMEField;
        
        private string eMPRESOURCE_SYSNAMEField;
        
        private string eMPCATEGORY_SYSNAMEField;
        
        private string gENREF1_SYSNAMEField;
        
        private string gENREF2_SYSNAMEField;
        
        private string gENREF3_SYSNAMEField;
        
        private string gENREF4_SYSNAMEField;
        
        private string gENREF5_SYSNAMEField;
        
        private string lEVEL1_SYSNAMEField;
        
        private string rESOURCE_ID_SYSNAMEField;
        
        private string rESOURCE_TYPE_SYSNAMEField;
        
        private string rESOURCE_SYSNAMEField;
        
        private string vENDOR_SYSNAMEField;
        
        private string mEDIA_VENDOR_SYSNAMEField;
        
        private string sALESPERSON_SYSNAMEField;
        
        private string cOMMITBUDGET_SYSNAMEField;
        
        private string cOMMITEDBUDGET_SYSNAMEField;
        
        private string pRESENTTOCLIENT_SYSNAMEField;
        
        private string pRESENTEDTOCLIENT_SYSNAMEField;
        
        private string rESOURCE_SCHEDULE_RATE1Field;
        
        private string rESOURCE_SCHEDULE_RATE2Field;
        
        private string rESOURCE_SCHEDULE_RATE3Field;
        
        private string rESOURCE_SCHEDULE_RATE4Field;
        
        private string bUDGET_SYSNAMEField;
        
        private string bUDGETED_SYSNAMEField;
        
        private string rESUSAGE_SYSNAMEField;
        
        private string dOCCTRLNUMBER_SYSNAMEField;
        
        private string rESOURCEID_SYSNAMEField;
        
        private string rESOURCETYPE_SYSNAMEField;
        
        private string sOFTBOOK_SYSNAMEField;
        
        private string hARDBOOK_SYSNAMEField;
        
        private string aMT1_SYSNAMEField;
        
        private string aMT3_SYSNAMEField;
        
        private string uNITS1_SYSNAMEField;
        
        private string wORKFLOW_SYSNAMEField;
        
        private string pRE_SCHEDULED_SYSNAMEField;
        
        private string nON_SCHEDULED_SYSNAMEField;
        
        private string sCHEDULED_SYSNAMEField;
        
        private string pENDING_APPROVAL_SYSNAMEField;
        
        private string pROJ_MANAGER_SYSNAMEField;
        
        private string wORKFLOW_END_DATEField;
        
        private string pO_EXTRA_PARAM_1Field;
        
        private string pO_EXTRA_PARAM_2Field;
        
        private string pO_EXTRA_PARAM_3Field;
        
        private string pO_EXTRA_PARAM_4Field;
        
        private string pO_EXTRA_PARAM_5Field;
        
        private string rEFERENCE_SYSNAMEField;
        
        private string pOSITION_CATEGORYField;
        
        private string cLIENT_PRODUCT_SYSNAMEField;
        
        private string mENU_EXPANDField;
        
        private string mENU_COLLAPSEField;
        
        private string pO_ACCOUNT_SERVICESField;
        
        private string pO_FUNCTIONAL_REPField;
        
        private string mEDIA_BUDGET_REF_1Field;
        
        private string mEDIA_BUDGET_REF_2Field;
        
        private string mEDIA_BUDGET_REF_3Field;
        
        private string cOST_CODE_NAMEField;
        
        private string eXPENSE_REPORT_TEXT1Field;
        
        private string eXPENSE_REPORT_NUMERIC1Field;
        
        private string gST_TAXField;
        
        private string supervisor_SysNameField;
        
        private string mEDIA_SYSNAMEField;
        
        private string rOLES_SYSNAMEField;
        
        private string fOB_SYSNAMEField;
        
        private string sERVICE_TYPE_UOMField;
        
        private string eXT_COSTField;
        
        private string uOMField;
        
        private string rATEField;
        
        private NameValue[] sysNamesField;
        
        /// <remarks/>
        public string LEVEL2_SYSNAME {
            get {
                return this.lEVEL2_SYSNAMEField;
            }
            set {
                this.lEVEL2_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string LEVEL3_SYSNAME {
            get {
                return this.lEVEL3_SYSNAMEField;
            }
            set {
                this.lEVEL3_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string ORG_UNIT_SYSNAME {
            get {
                return this.oRG_UNIT_SYSNAMEField;
            }
            set {
                this.oRG_UNIT_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string LOCATION_SYSNAME {
            get {
                return this.lOCATION_SYSNAMEField;
            }
            set {
                this.lOCATION_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string COMPANY_SYSNAME {
            get {
                return this.cOMPANY_SYSNAMEField;
            }
            set {
                this.cOMPANY_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string CLIENT_SYSNAME {
            get {
                return this.cLIENT_SYSNAMEField;
            }
            set {
                this.cLIENT_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string POSITION_SYSNAME {
            get {
                return this.pOSITION_SYSNAMEField;
            }
            set {
                this.pOSITION_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string TASK_SYSNAME {
            get {
                return this.tASK_SYSNAMEField;
            }
            set {
                this.tASK_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string DEPARTMENT_SYSNAME {
            get {
                return this.dEPARTMENT_SYSNAMEField;
            }
            set {
                this.dEPARTMENT_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string CLASS_SYSNAME {
            get {
                return this.cLASS_SYSNAMEField;
            }
            set {
                this.cLASS_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string EXPTYPES_SYSNAME_NAME {
            get {
                return this.eXPTYPES_SYSNAME_NAMEField;
            }
            set {
                this.eXPTYPES_SYSNAME_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string EXPTYPES_SYSNAME {
            get {
                return this.eXPTYPES_SYSNAMEField;
            }
            set {
                this.eXPTYPES_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string EMPRESOURCE_SYSNAME {
            get {
                return this.eMPRESOURCE_SYSNAMEField;
            }
            set {
                this.eMPRESOURCE_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string EMPCATEGORY_SYSNAME {
            get {
                return this.eMPCATEGORY_SYSNAMEField;
            }
            set {
                this.eMPCATEGORY_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string GENREF1_SYSNAME {
            get {
                return this.gENREF1_SYSNAMEField;
            }
            set {
                this.gENREF1_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string GENREF2_SYSNAME {
            get {
                return this.gENREF2_SYSNAMEField;
            }
            set {
                this.gENREF2_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string GENREF3_SYSNAME {
            get {
                return this.gENREF3_SYSNAMEField;
            }
            set {
                this.gENREF3_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string GENREF4_SYSNAME {
            get {
                return this.gENREF4_SYSNAMEField;
            }
            set {
                this.gENREF4_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string GENREF5_SYSNAME {
            get {
                return this.gENREF5_SYSNAMEField;
            }
            set {
                this.gENREF5_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string LEVEL1_SYSNAME {
            get {
                return this.lEVEL1_SYSNAMEField;
            }
            set {
                this.lEVEL1_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string RESOURCE_ID_SYSNAME {
            get {
                return this.rESOURCE_ID_SYSNAMEField;
            }
            set {
                this.rESOURCE_ID_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string RESOURCE_TYPE_SYSNAME {
            get {
                return this.rESOURCE_TYPE_SYSNAMEField;
            }
            set {
                this.rESOURCE_TYPE_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string RESOURCE_SYSNAME {
            get {
                return this.rESOURCE_SYSNAMEField;
            }
            set {
                this.rESOURCE_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string VENDOR_SYSNAME {
            get {
                return this.vENDOR_SYSNAMEField;
            }
            set {
                this.vENDOR_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string MEDIA_VENDOR_SYSNAME {
            get {
                return this.mEDIA_VENDOR_SYSNAMEField;
            }
            set {
                this.mEDIA_VENDOR_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string SALESPERSON_SYSNAME {
            get {
                return this.sALESPERSON_SYSNAMEField;
            }
            set {
                this.sALESPERSON_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string COMMITBUDGET_SYSNAME {
            get {
                return this.cOMMITBUDGET_SYSNAMEField;
            }
            set {
                this.cOMMITBUDGET_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string COMMITEDBUDGET_SYSNAME {
            get {
                return this.cOMMITEDBUDGET_SYSNAMEField;
            }
            set {
                this.cOMMITEDBUDGET_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PRESENTTOCLIENT_SYSNAME {
            get {
                return this.pRESENTTOCLIENT_SYSNAMEField;
            }
            set {
                this.pRESENTTOCLIENT_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PRESENTEDTOCLIENT_SYSNAME {
            get {
                return this.pRESENTEDTOCLIENT_SYSNAMEField;
            }
            set {
                this.pRESENTEDTOCLIENT_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string RESOURCE_SCHEDULE_RATE1 {
            get {
                return this.rESOURCE_SCHEDULE_RATE1Field;
            }
            set {
                this.rESOURCE_SCHEDULE_RATE1Field = value;
            }
        }
        
        /// <remarks/>
        public string RESOURCE_SCHEDULE_RATE2 {
            get {
                return this.rESOURCE_SCHEDULE_RATE2Field;
            }
            set {
                this.rESOURCE_SCHEDULE_RATE2Field = value;
            }
        }
        
        /// <remarks/>
        public string RESOURCE_SCHEDULE_RATE3 {
            get {
                return this.rESOURCE_SCHEDULE_RATE3Field;
            }
            set {
                this.rESOURCE_SCHEDULE_RATE3Field = value;
            }
        }
        
        /// <remarks/>
        public string RESOURCE_SCHEDULE_RATE4 {
            get {
                return this.rESOURCE_SCHEDULE_RATE4Field;
            }
            set {
                this.rESOURCE_SCHEDULE_RATE4Field = value;
            }
        }
        
        /// <remarks/>
        public string BUDGET_SYSNAME {
            get {
                return this.bUDGET_SYSNAMEField;
            }
            set {
                this.bUDGET_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string BUDGETED_SYSNAME {
            get {
                return this.bUDGETED_SYSNAMEField;
            }
            set {
                this.bUDGETED_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string RESUSAGE_SYSNAME {
            get {
                return this.rESUSAGE_SYSNAMEField;
            }
            set {
                this.rESUSAGE_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string DOCCTRLNUMBER_SYSNAME {
            get {
                return this.dOCCTRLNUMBER_SYSNAMEField;
            }
            set {
                this.dOCCTRLNUMBER_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string RESOURCEID_SYSNAME {
            get {
                return this.rESOURCEID_SYSNAMEField;
            }
            set {
                this.rESOURCEID_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string RESOURCETYPE_SYSNAME {
            get {
                return this.rESOURCETYPE_SYSNAMEField;
            }
            set {
                this.rESOURCETYPE_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string SOFTBOOK_SYSNAME {
            get {
                return this.sOFTBOOK_SYSNAMEField;
            }
            set {
                this.sOFTBOOK_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string HARDBOOK_SYSNAME {
            get {
                return this.hARDBOOK_SYSNAMEField;
            }
            set {
                this.hARDBOOK_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string AMT1_SYSNAME {
            get {
                return this.aMT1_SYSNAMEField;
            }
            set {
                this.aMT1_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string AMT3_SYSNAME {
            get {
                return this.aMT3_SYSNAMEField;
            }
            set {
                this.aMT3_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string UNITS1_SYSNAME {
            get {
                return this.uNITS1_SYSNAMEField;
            }
            set {
                this.uNITS1_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string WORKFLOW_SYSNAME {
            get {
                return this.wORKFLOW_SYSNAMEField;
            }
            set {
                this.wORKFLOW_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PRE_SCHEDULED_SYSNAME {
            get {
                return this.pRE_SCHEDULED_SYSNAMEField;
            }
            set {
                this.pRE_SCHEDULED_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string NON_SCHEDULED_SYSNAME {
            get {
                return this.nON_SCHEDULED_SYSNAMEField;
            }
            set {
                this.nON_SCHEDULED_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string SCHEDULED_SYSNAME {
            get {
                return this.sCHEDULED_SYSNAMEField;
            }
            set {
                this.sCHEDULED_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PENDING_APPROVAL_SYSNAME {
            get {
                return this.pENDING_APPROVAL_SYSNAMEField;
            }
            set {
                this.pENDING_APPROVAL_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string PROJ_MANAGER_SYSNAME {
            get {
                return this.pROJ_MANAGER_SYSNAMEField;
            }
            set {
                this.pROJ_MANAGER_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string WORKFLOW_END_DATE {
            get {
                return this.wORKFLOW_END_DATEField;
            }
            set {
                this.wORKFLOW_END_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string PO_EXTRA_PARAM_1 {
            get {
                return this.pO_EXTRA_PARAM_1Field;
            }
            set {
                this.pO_EXTRA_PARAM_1Field = value;
            }
        }
        
        /// <remarks/>
        public string PO_EXTRA_PARAM_2 {
            get {
                return this.pO_EXTRA_PARAM_2Field;
            }
            set {
                this.pO_EXTRA_PARAM_2Field = value;
            }
        }
        
        /// <remarks/>
        public string PO_EXTRA_PARAM_3 {
            get {
                return this.pO_EXTRA_PARAM_3Field;
            }
            set {
                this.pO_EXTRA_PARAM_3Field = value;
            }
        }
        
        /// <remarks/>
        public string PO_EXTRA_PARAM_4 {
            get {
                return this.pO_EXTRA_PARAM_4Field;
            }
            set {
                this.pO_EXTRA_PARAM_4Field = value;
            }
        }
        
        /// <remarks/>
        public string PO_EXTRA_PARAM_5 {
            get {
                return this.pO_EXTRA_PARAM_5Field;
            }
            set {
                this.pO_EXTRA_PARAM_5Field = value;
            }
        }
        
        /// <remarks/>
        public string REFERENCE_SYSNAME {
            get {
                return this.rEFERENCE_SYSNAMEField;
            }
            set {
                this.rEFERENCE_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string POSITION_CATEGORY {
            get {
                return this.pOSITION_CATEGORYField;
            }
            set {
                this.pOSITION_CATEGORYField = value;
            }
        }
        
        /// <remarks/>
        public string CLIENT_PRODUCT_SYSNAME {
            get {
                return this.cLIENT_PRODUCT_SYSNAMEField;
            }
            set {
                this.cLIENT_PRODUCT_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string MENU_EXPAND {
            get {
                return this.mENU_EXPANDField;
            }
            set {
                this.mENU_EXPANDField = value;
            }
        }
        
        /// <remarks/>
        public string MENU_COLLAPSE {
            get {
                return this.mENU_COLLAPSEField;
            }
            set {
                this.mENU_COLLAPSEField = value;
            }
        }
        
        /// <remarks/>
        public string PO_ACCOUNT_SERVICES {
            get {
                return this.pO_ACCOUNT_SERVICESField;
            }
            set {
                this.pO_ACCOUNT_SERVICESField = value;
            }
        }
        
        /// <remarks/>
        public string PO_FUNCTIONAL_REP {
            get {
                return this.pO_FUNCTIONAL_REPField;
            }
            set {
                this.pO_FUNCTIONAL_REPField = value;
            }
        }
        
        /// <remarks/>
        public string MEDIA_BUDGET_REF_1 {
            get {
                return this.mEDIA_BUDGET_REF_1Field;
            }
            set {
                this.mEDIA_BUDGET_REF_1Field = value;
            }
        }
        
        /// <remarks/>
        public string MEDIA_BUDGET_REF_2 {
            get {
                return this.mEDIA_BUDGET_REF_2Field;
            }
            set {
                this.mEDIA_BUDGET_REF_2Field = value;
            }
        }
        
        /// <remarks/>
        public string MEDIA_BUDGET_REF_3 {
            get {
                return this.mEDIA_BUDGET_REF_3Field;
            }
            set {
                this.mEDIA_BUDGET_REF_3Field = value;
            }
        }
        
        /// <remarks/>
        public string COST_CODE_NAME {
            get {
                return this.cOST_CODE_NAMEField;
            }
            set {
                this.cOST_CODE_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string EXPENSE_REPORT_TEXT1 {
            get {
                return this.eXPENSE_REPORT_TEXT1Field;
            }
            set {
                this.eXPENSE_REPORT_TEXT1Field = value;
            }
        }
        
        /// <remarks/>
        public string EXPENSE_REPORT_NUMERIC1 {
            get {
                return this.eXPENSE_REPORT_NUMERIC1Field;
            }
            set {
                this.eXPENSE_REPORT_NUMERIC1Field = value;
            }
        }
        
        /// <remarks/>
        public string GST_TAX {
            get {
                return this.gST_TAXField;
            }
            set {
                this.gST_TAXField = value;
            }
        }
        
        /// <remarks/>
        public string supervisor_SysName {
            get {
                return this.supervisor_SysNameField;
            }
            set {
                this.supervisor_SysNameField = value;
            }
        }
        
        /// <remarks/>
        public string MEDIA_SYSNAME {
            get {
                return this.mEDIA_SYSNAMEField;
            }
            set {
                this.mEDIA_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string ROLES_SYSNAME {
            get {
                return this.rOLES_SYSNAMEField;
            }
            set {
                this.rOLES_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string FOB_SYSNAME {
            get {
                return this.fOB_SYSNAMEField;
            }
            set {
                this.fOB_SYSNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string SERVICE_TYPE_UOM {
            get {
                return this.sERVICE_TYPE_UOMField;
            }
            set {
                this.sERVICE_TYPE_UOMField = value;
            }
        }
        
        /// <remarks/>
        public string EXT_COST {
            get {
                return this.eXT_COSTField;
            }
            set {
                this.eXT_COSTField = value;
            }
        }
        
        /// <remarks/>
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        public string RATE {
            get {
                return this.rATEField;
            }
            set {
                this.rATEField = value;
            }
        }
        
        /// <remarks/>
        public NameValue[] SysNames {
            get {
                return this.sysNamesField;
            }
            set {
                this.sysNamesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Paradigm.Esm.WebService")]
    public enum REFERENCE_DATA_RECORD_TYPE {
        
        /// <remarks/>
        LOCATION,
        
        /// <remarks/>
        EMPLOYEE_TYPE,
        
        /// <remarks/>
        EXPENSE_TYPE,
        
        /// <remarks/>
        TASK_TYPE,
        
        /// <remarks/>
        ORG_UNIT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Paradigm.Esm.WebService")]
    public enum REPORTING_DATA_RECORD_TYPE {
        
        /// <remarks/>
        DATA_RECORD_TYPE_1,
        
        /// <remarks/>
        DATA_RECORD_TYPE_2,
        
        /// <remarks/>
        DATA_RECORD_TYPE_3,
        
        /// <remarks/>
        DATA_RECORD_TYPE_4,
        
        /// <remarks/>
        DATA_RECORD_TYPE_5,
        
        /// <remarks/>
        JOB_COST_DETAIL,
        
        /// <remarks/>
        CLIENT_PROFILE_APPROVALS,
        
        /// <remarks/>
        LEVEL1_APPROVALS,
        
        /// <remarks/>
        LEVEL2_APPROVALS,
        
        /// <remarks/>
        BUDGET_L2_L3_APPROVALS,
        
        /// <remarks/>
        IO_BUDGET_APPROVALS,
        
        /// <remarks/>
        EXPENSE_SUMMARY,
        
        /// <remarks/>
        EXPENSE_SUMMARY_CHART,
        
        /// <remarks/>
        TIME_SUMMARY,
        
        /// <remarks/>
        TIME_SUMMARY_CHART,
        
        /// <remarks/>
        RM_EMP_WORKLOAD_BY_WEEK_CHART,
        
        /// <remarks/>
        RM_MGR_WORKLOAD_BY_WEEK_CHART,
        
        /// <remarks/>
        WORKFLOW_ALLOCATION,
        
        /// <remarks/>
        TIME_UTILIZATION_CHART,
        
        /// <remarks/>
        YEAR_TO_DATE_REVENUE,
        
        /// <remarks/>
        CLIENT_REVENUE,
        
        /// <remarks/>
        TIME_SUMMARY_STATUS,
        
        /// <remarks/>
        CLIENTS_HOURS_BY_MONTH,
        
        /// <remarks/>
        BUDGET_L2_STATUS,
        
        /// <remarks/>
        BUDGET_L2_APPROVALS,
        
        /// <remarks/>
        FR_REVENUE_MEDIA_CLIENT,
        
        /// <remarks/>
        SSO_SITES_USER,
        
        /// <remarks/>
        SSO_TOOL_SITES,
        
        /// <remarks/>
        REVENUE_MEDIA_VENDOR,
        
        /// <remarks/>
        REVENUE_MEDIA_CLIENT,
        
        /// <remarks/>
        LEVEL2_NO_BUDGET,
        
        /// <remarks/>
        RESOURCE_EMAILS,
        
        /// <remarks/>
        UNPOSTED_VOUCHERS,
        
        /// <remarks/>
        WEEKLY_RM_ALLOCATION_DAYWISE,
        
        /// <remarks/>
        MYTIME_HOURS_GADGET,
        
        /// <remarks/>
        PO_APPROVAL,
        
        /// <remarks/>
        MONTHLY_RM_ALLOCATION_QUARTER,
        
        /// <remarks/>
        BUDGET_ORDER_NOTIFICATIONS,
        
        /// <remarks/>
        BUDGET_ORDER_PENDING,
        
        /// <remarks/>
        API_INVOICES,
        
        /// <remarks/>
        TIME_UTILIZATION_SUMMARY,
        
        /// <remarks/>
        PTO_SUMMARY,
        
        /// <remarks/>
        TIME_ANALYSIS,
        
        /// <remarks/>
        GTO_PTO_SUMMARY,
        
        /// <remarks/>
        LEVEL2_ACTIVE_LIST,
        
        /// <remarks/>
        REVENUE_BY_CLIENTS,
        
        /// <remarks/>
        REVENUE_TARGETS_ACTUAL,
        
        /// <remarks/>
        MANPOWER_ANALYSIS,
        
        /// <remarks/>
        AGENCY_CLIENT_P_AND_L,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Paradigm.Esm.WebService")]
    public enum ACTION_TYPE {
        
        /// <remarks/>
        TIMESHEET_APPROVAL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetEditionCompletedEventHandler(object sender, GetEditionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEditionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEditionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetVersionCompletedEventHandler(object sender, GetVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetReleaseDateCompletedEventHandler(object sender, GetReleaseDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReleaseDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReleaseDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AuthenticateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetInstalledCompanyListCompletedEventHandler(object sender, GetInstalledCompanyListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInstalledCompanyListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInstalledCompanyListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompanyLight[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompanyLight[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void IsAuthenticatedCompletedEventHandler(object sender, IsAuthenticatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsAuthenticatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsAuthenticatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetAuthenticationTokenCompletedEventHandler(object sender, GetAuthenticationTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAuthenticationTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAuthenticationTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthToken Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthToken)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetTrxTypesCompletedEventHandler(object sender, GetTrxTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTrxTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTrxTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TrxType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TrxType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetReferenceDataRecordsCompletedEventHandler(object sender, GetReferenceDataRecordsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReferenceDataRecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReferenceDataRecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataRecords Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataRecords)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetReferenceAvailableFieldListCompletedEventHandler(object sender, GetReferenceAvailableFieldListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReferenceAvailableFieldListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReferenceAvailableFieldListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FieldAttribute[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FieldAttribute[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetReportingAvailableParametersCompletedEventHandler(object sender, GetReportingAvailableParametersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportingAvailableParametersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportingAvailableParametersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FieldAttribute[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FieldAttribute[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetReportingDataRecordsCompletedEventHandler(object sender, GetReportingDataRecordsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportingDataRecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportingDataRecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataRecords Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataRecords)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetSysNameCompletedEventHandler(object sender, GetSysNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSysNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSysNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ReplaceWithGenNamesCompletedEventHandler(object sender, ReplaceWithGenNamesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReplaceWithGenNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReplaceWithGenNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void PerformActionCompletedEventHandler(object sender, PerformActionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerformActionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PerformActionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetExpenseTransactionImageCompletedEventHandler(object sender, GetExpenseTransactionImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExpenseTransactionImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExpenseTransactionImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SetExpenseTransactionImageCompletedEventHandler(object sender, SetExpenseTransactionImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetExpenseTransactionImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetExpenseTransactionImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591