

IF EXISTS (select * from sys.procedures where name='pdsw_apps_subscribers_get_list')
DROP PROCEDURE pdsw_apps_subscribers_get_list
GO
CREATE PROCEDURE pdsw_apps_subscribers_get_list
AS
SELECT 
DISTINCT
APN.SUBSCRIBER_ID
,APSI.TIMEZONE
FROM PDD_APPS_NOTIFICATION APN 
INNER JOIN PDD_APPS_SUBSCRIBER_INFO APSI
ON APN.SUBSCRIBER_ID=APSI.SUBSCRIBER_ID
WHERE ISNULL(APN.WRITE_FLAG,'')='' AND ISNULL(APN.DELETE_FLAG, '') <> 1 AND APN.CREATE_DATE >= DATEADD(DAY,-1, GETDATE())

GO

